
# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        project: [proj_a, proj_b]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: my-files-${{ matrix.project }}
          path: files

  release:
    #if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download files
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: |
      #      files/*
      #      README.md
      #    name: ${{ github.ref }}_test

